server:
  port: 8080

spring:
  application:
    name: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
  datasource:
    url: jdbc:sqlserver://172.20.200.158:1433;databaseName=SENEGAL;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Contec@1234
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
